# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x1a\nbase.proto\"A\n\x08UserItem\x12\x13\n\x02id\x18\x01 \x01(\x0b\x32\x07.UserID\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nlastactive\x18\x03 \x01(\t\"\x14\n\x06UserID\x12\n\n\x02id\x18\x01 \x01(\t2Q\n\x04User\x12$\n\x0bGetAllUsers\x12\x06.Empty\x1a\t.UserItem\"\x00\x30\x01\x12#\n\x0bGetUserById\x12\x07.UserID\x1a\t.UserItem\"\x00\x62\x06proto3')



_USERITEM = DESCRIPTOR.message_types_by_name['UserItem']
_USERID = DESCRIPTOR.message_types_by_name['UserID']
UserItem = _reflection.GeneratedProtocolMessageType('UserItem', (_message.Message,), {
  'DESCRIPTOR' : _USERITEM,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:UserItem)
  })
_sym_db.RegisterMessage(UserItem)

UserID = _reflection.GeneratedProtocolMessageType('UserID', (_message.Message,), {
  'DESCRIPTOR' : _USERID,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:UserID)
  })
_sym_db.RegisterMessage(UserID)

_USER = DESCRIPTOR.services_by_name['User']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERITEM._serialized_start=26
  _USERITEM._serialized_end=91
  _USERID._serialized_start=93
  _USERID._serialized_end=113
  _USER._serialized_start=115
  _USER._serialized_end=196
# @@protoc_insertion_point(module_scope)
