# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2
import user_pb2 as user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\x1a\nbase.proto\x1a\nuser.proto\"6\n\x0b\x42ookingData\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x17\n\x04\x64\x61te\x18\x02 \x03(\x0b\x32\t.DateItem\"*\n\x08\x44\x61teItem\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x10\n\x08moviesId\x18\x02 \x03(\t2d\n\x07\x42ooking\x12*\n\x0eGetAllBookings\x12\x06.Empty\x1a\x0c.BookingData\"\x00\x30\x01\x12-\n\x12GetBookingByUserId\x12\x07.UserID\x1a\x0c.BookingData\"\x00\x62\x06proto3')



_BOOKINGDATA = DESCRIPTOR.message_types_by_name['BookingData']
_DATEITEM = DESCRIPTOR.message_types_by_name['DateItem']
BookingData = _reflection.GeneratedProtocolMessageType('BookingData', (_message.Message,), {
  'DESCRIPTOR' : _BOOKINGDATA,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:BookingData)
  })
_sym_db.RegisterMessage(BookingData)

DateItem = _reflection.GeneratedProtocolMessageType('DateItem', (_message.Message,), {
  'DESCRIPTOR' : _DATEITEM,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:DateItem)
  })
_sym_db.RegisterMessage(DateItem)

_BOOKING = DESCRIPTOR.services_by_name['Booking']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOKINGDATA._serialized_start=41
  _BOOKINGDATA._serialized_end=95
  _DATEITEM._serialized_start=97
  _DATEITEM._serialized_end=139
  _BOOKING._serialized_start=141
  _BOOKING._serialized_end=241
# @@protoc_insertion_point(module_scope)
